spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/console-log?useSSL=false&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true"
    username: "root"
    password: "12345678"
  jpa:
    database: mysql
    hibernate:
      ddl-auto: #  validate, none
    properties:
      hibernate:
        format_sql: true
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
